### ISSUE TITLE
fixes necessary

### ISSUE THREAD

**Issue by knutsack** [jefflomacy/villagerdb#113]
things that I've noticed:
-Wooden Washtub image isn't png of item, instead pic from diy page
-Wall-mounted TV (20in) and (50in) dont have images
-Winnie's poster and picture are in the Indoor/Outdoor Items category instead of the Photos category
-There is an additional item titled "Gray-struped Wall" with no image. This needs to be removed.
-There is 2 "Joined-mat Flooring" items. 
-"Nook Inc. Botanical Rug" has no image.
-There is an item titled "Stirped Flooring" that needs to be removed.
-"Café K.K.", "K.K. D&B", "K.K. Étude" all have non-png images.
-There is a fish titled "Cruician Carp" that needs to be removed.
-There is a fossil titled "Corpolite" that needs to be removed.
-There are 2 each of "Opthalmo Skull" and "Opthalmo Torso". Remove the ones with no image.
-The "Stache and Glasses" that shows up when filtered by Horizons items has the New Leaf image.
-The dresses titled "Orange Dress" and "Wood-egg Outfit" have no image.
-The hats titled "Bunny Day Crown", "Orange Hat" have no image.
-There are 2 hats titled "Paisley Bandana". Remove the one with no image.
-The top titled "Café Uniform" that shows up when filtered by Horizons items has the New Leaf image.
-The top titled "Hard-knit Tank" needs to be removed.
-The top titled "Privét Tee" has no image.
-The villagers Audie and Megan have non-png images.
-Many of the ACNL flowers have the ACNH image.
-The flowers titled "Orange Hyacinths", "Orange Lilies", "Orange Roses", "Orange Tulips", and "Orange Windflowers" have no image.
-The fruits titled "Apple" and "Orange" have the wrong images assigned to the items.

**Comment by Avalai** [comment]
Various posters are listed at the end of a search for "Poster" even though they shouldn't be, alphabetically. (https://villagerdb.com/search/page/18?q=Poster)

I can't find the My Melody poster in the list at all, though it does have a listing on the site.

Missing poster images:
- Pavé's Poster
- Renée's Poster
- Kiki & Lala poster

**Comment by jefflomacy** [comment]
The sorting is actually based on relevance, and the tie breaker for relevance is alphabetical sorting. The behavior you're seeing here is what I would expect. 

I was able to find the My Melody poster on the last page. Apparently because it has even more tokens ElasticSearch decided it is further irrelevant, thus placing it near the end of the search: https://villagerdb.com/search/page/19?q=poster

This does raise a good point that we should probably allow sorting by pure alphabetical as well as relevancy. 

Thanks for the heads up on the missing images -- likely just misnamed files not matching the entity ID.

**Comment by jefflomacy** [comment]
In ticket #116 I will implement a health check we can run in production to root out the rest of the missing media files hopefully.

**Comment by trundleroo** [comment]
Most of these issues have been fixed. We still need to clean up some of the JSON data (such as duplicates that we need to manually delete).
